let shopItemsData = [
  {
    id: "a",
    name: "Australian Shepherd",
    price: 900,
    img: "images/australianshepherd.png",
  },
  {
    id: "b",
    name: "Pembroke Welsh Corgi",
    price: 1000,
    img: "images/pembrokewelshcorgi.png",
  },
  {
    id: "c",
    name: "Chow Chow",
    price: 1200,
    img: "images/chowchow.png",
  },
  {
    id: "d",
    name: "Maltipoo",
    price: 900,
    img: "images/maltipoo.png",
  },
  {
    id: "e",
    name: "Pug",
    price: 700,
    img: "images/pug.png",
  },
  {
      id: "f",
    name: "Shih Tzu",
    price: 500,
    img: "images/shihtzu.png",
  },
    {
    id: "g",
    name: "Border Collie",
    price: 500,
    img: "images/bordercollie.png",
  },
  {
    id: "h",
    name: "Siberian Husky",
    price: 900,
    img: "images/siberianhusky.png",
  },  {
    id: "i",
    name: "American Staffordshire Terrier",
    price: 1600,
    img: "images/americanstaffordshireterrier.png",
  },
  {
    id: "j",
    name: "Beagle",
    price: 800,
    img: "images/beagle.png",
  },  {
    id: "k",
    name: "French Bulldog",
    price: 1100,
    img: "images/frenchbulldog.png",
  },
  {
    id: "l",
    name: "Golden Retriever",
    price: 350,
    img: "images/goldenretriever.png",
  },  {
    id: "m",
    name: "Shetland Sheepdog",
    price: 900,
    img: "images/shetlandsheepdog.png",
  },
  {
    id: "n",
    name: "Yorkshire Terrier",
    price: 1700,
    img: "images/yorkshireterrier.png",
  },  {
    id: "o",
    name: "Dachshund",
    price: 1300,
    img: "images/dachshund.png",
  },
  {
    id: "p",
    name: "Shiba Inu",
    price: 1100,
    img: "images/shibainu.png",
  },  {
    id: "q",
    name: "Portuguese Water Dog",
    price: 2000,
    img: "images/portuguesewaterdog.png",
  },
  {
    id: "r",
    name: "Bernese Mountain Dog",
    price: 1300,
    img: "images/bernesemountaindog.png",
  },  {
    id: "s",
    name: "Labrador Retriever",
    price: 500,
    img: "images/labradorretriever.png",
  },
  {
    id: "t",
    name: "Dalmatian",
    price: 500,
    img: "images/dalmatian.png",
  },  {
    id: "u",
    name: "Staffordshire Bull Terrier",
    price: 1500,
    img: "images/staffordshirebullterrier.png",
  },
  {
    id: "v",
    name: "German Shepherd",
    price: 800,
    img: "images/germanshepherd.png",
  },  {
    id: "w",
    name: "Doberman Pinscher",
    price: 1000,
    img: "images/dobermanpinscher.png",
  },
  {
    id: "x",
    name: "Pomeranian",
    price: 800,
    img: "images/Pomeranian.png",
  },  {
    id: "y",
    name: "Jack Russell Terrier",
    price: 700,
    img: "images/jackrussellterrier.png",
  },
  {
    id: "z",
    name: "Chihuahua",
    price: 900,
    img: "images/chihuahua.png",
  },  {
    id: "aa",
    name: "Bichon Frise",
    price: 1000,
    img: "images/bichonfrise.png",
  },
  {
    id: "ab",
    name: "Miniature Pinscher",
    price: 800,
    img: "images/miniaturepinscher.png",
  },  {
    id: "ac",
    name: "Japanese Chin",
    price: 1300,
    img: "images/japanesechin.png",
  },
  {
    id: "ad",
    name: "Biewer Terrier",
    price: 2000,
    img: "images/biewerterrier.png",
  },
];